import type { Metadata } from "next";
import React from 'react';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Script e Configuração da API-Sports para Web Components */}
        <script type="module" src="https://widgets.api-sports.io/3.1.0/widgets.js" async />
        {React.createElement('api-sports-widget', {
          'data-type': 'config',
          'data-sport': 'football',
          'data-key': process.env.API_SPORTS_KEY || 'MISSING_API_KEY'
        })}
        
        {children}
      </body>
    </html>
  );
}
